### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by lunaisnotaboy** [darylhjd/mangodex#1]
Stupid question here, but is this the *official* API (e.g. the one currently live)?

**Comment by darylhjd** [comment]
nope!

**Comment by lunaisnotaboy** [comment]
Ah, okay. I really don't know what to believe given the recent leak. Thanks!

**Comment by darylhjd** [comment]
this is just a language wrapper, so you can still use it to interact with the _official_ API, but the wrapper itself isn't official
